using excecoesThrow;

try
{
    A.RenderA();
}
catch
{
    Console.WriteLine("Tratamento da exceção está na Main");
}


Console.ReadKey();